# Fly.io configuration for FarePlay Casino Backend
# Replace 'my-casino' with your casino name

app = "fareplay-casino"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[deploy]
  release_command = "npx prisma migrate deploy --schema=packages/db/prisma/schema.prisma"

[env]
  NODE_ENV = "production"
  API_HOST = "0.0.0.0"
  WS_HOST = "0.0.0.0"

# Process groups for different services
[processes]
  api = "node apps/api/dist/index.js"
  ws = "node apps/ws/dist/index.js"
  processor = "node apps/processor/dist/index.js"

# API service
[[services]]
  processes = ["api"]
  http_checks = []
  internal_port = 3000
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "10s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

# WebSocket service
[[services]]
  processes = ["ws"]
  http_checks = []
  internal_port = 3001
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 100
    soft_limit = 80
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 3001

# Processor service (background worker - no external ports)
[[services]]
  processes = ["processor"]
  internal_port = 8080

  [services.concurrency]
    type = "requests"
    hard_limit = 1
    soft_limit = 1

# Resource allocation
[vm]
  size = "shared-cpu-1x"
  memory = 512

# Metrics
[metrics]
  port = 9091
  path = "/metrics"


